
package org.example.bookingrest.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EventService", targetNamespace = "http://controller.bookingServicePayara.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EventService {


    /**
     * 
     * @param eventId
     * @throws TooLateToDelete_Exception
     * @throws InvalidParameter_Exception
     * @throws CustomNotFound_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEvent", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.DeleteEvent")
    @ResponseWrapper(localName = "deleteEventResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.DeleteEventResponse")
    public void deleteEvent(
        @WebParam(name = "event_id", targetNamespace = "")
        String eventId)
        throws CustomNotFound_Exception, InvalidParameter_Exception, TooLateToDelete_Exception
    ;

    /**
     * 
     * @param personId
     * @param ticketId
     * @return
     *     returns org.example.bookingrest.wsdl.Ticket
     * @throws InvalidParameter_Exception
     * @throws IncorrectParameter_Exception
     * @throws TicketServiceNotAvailable_Exception
     * @throws AlreadyVIPException_Exception
     * @throws MultipleNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copyTicketWithDoublePriceAndVip", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.CopyTicketWithDoublePriceAndVip")
    @ResponseWrapper(localName = "copyTicketWithDoublePriceAndVipResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.CopyTicketWithDoublePriceAndVipResponse")
    public Ticket copyTicketWithDoublePriceAndVip(
        @WebParam(name = "ticket_id", targetNamespace = "")
        String ticketId,
        @WebParam(name = "person_id", targetNamespace = "")
        String personId)
        throws AlreadyVIPException_Exception, IncorrectParameter_Exception, InvalidParameter_Exception, MultipleNotFound_Exception, TicketServiceNotAvailable_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.example.bookingrest.wsdl.TicketWithEventWrite
     * @throws InvalidParameter_Exception
     * @throws CustomNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetTicket")
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetTicketResponse")
    public TicketWithEventWrite getTicket(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws CustomNotFound_Exception, InvalidParameter_Exception
    ;

    /**
     * 
     * @return
     *     returns org.example.bookingrest.wsdl.EventReadList
     * @throws CustomNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEvents", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetAllEvents")
    @ResponseWrapper(localName = "getAllEventsResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetAllEventsResponse")
    public EventReadList getAllEvents()
        throws CustomNotFound_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.example.bookingrest.wsdl.Person
     * @throws InvalidParameter_Exception
     * @throws CustomNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetPersonResponse")
    public Person getPerson(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws CustomNotFound_Exception, InvalidParameter_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQwe", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetQwe")
    @ResponseWrapper(localName = "getQweResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetQweResponse")
    public String getQwe();

    /**
     * 
     * @param eventWrite
     * @return
     *     returns org.example.bookingrest.wsdl.Event
     * @throws TicketServiceNotAvailable_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEvent", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.AddEvent")
    @ResponseWrapper(localName = "addEventResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.AddEventResponse")
    public Event addEvent(
        @WebParam(name = "eventWrite", targetNamespace = "")
        EventWrite eventWrite)
        throws TicketServiceNotAvailable_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns org.example.bookingrest.wsdl.EventRead
     * @throws InvalidParameter_Exception
     * @throws CustomNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEvent", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetEvent")
    @ResponseWrapper(localName = "getEventResponse", targetNamespace = "http://controller.bookingServicePayara.example.com/", className = "org.example.bookingrest.wsdl.GetEventResponse")
    public EventRead getEvent(
        @WebParam(name = "id", targetNamespace = "")
        String id)
        throws CustomNotFound_Exception, InvalidParameter_Exception
    ;

}
